[package]
name = "mykobo-rs"
version = "0.0.15"
edition = "2021"
repository = "https://github.com/mykobo/mykobo-rs"
description = "A MYKOBO API client written in Rust, to interact with the MYKOBO suite of services."
license-file = "LICENSE"
publish = false

[dependencies]
aws-config = { version = "1.6.2", features = ["behavior-version-latest"] }
aws-sdk-sqs = { version = "1.66.0" }
chrono = { version = "0.4.41", features = ["serde"] }
jsonwebtoken = "9.3.1"
log = "0.4.27"
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.39.2" }
uuid = { version = "1.16.0", features = ["v4"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
tokio = { version = "1.41.1", features = ["test-util"] }
wiremock = "0.6.2"
reqwest = { version = "0.12.4", features = ["json"] }
fake = { version = "4.3.0", features = ["ulid"] }
