[package]
name = "mykobo-rs"
version = "0.0.7"
edition = "2021"
repository = "https://github.com/mykobo/mykobo-rs"
description = "A MYKOBO API client written in Rust, to interact with the MYKOBO suite of services."
license-file = "LICENSE"
publish = false

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
jsonwebtoken = "9.3.0"
log = "0.4.21"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
tokio = { version = "1.39.2" }

[dev-dependencies]
test-log = "0.2.16"
pretty_assertions = "1.4.0"
tokio = { version = "1.41.1", features = ["test-util"] }
asserhttp = { version = "0.7.1", features = ["reqwest"] }
wiremock = "0.6.2"
reqwest = { version = "0.12.4", features = ["json"] }
fake = { version = "3.0.1", features = ["ulid"] }
